fixtures:
    forge_modules:
      stdlib:
        repo: "puppetlabs/stdlib"
        ref: "4.17.1"
        flags: "--module_repository=https://forge.puppet.com"
      augeasproviders_pam:
        repo: "herculesteam/augeasproviders_pam"
        ref: "2.1.0"
        flags: "--module_repository=https://forge.puppet.com"
      augeasproviders_core:
        repo: "herculesteam/augeasproviders_core"
        ref: "2.1.3"
        flags: "--module_repository=https://forge.puppet.com"
      sysctl:
        repo: "fiddyspence/sysctl"
        ref: "1.1.0"
        flags: "--module_repository=https://forge.puppet.com"
    symlinks:
        cis_rhel7: "#{source_dir}"
